url: http://monamideco.com.br
baseurl: /

# Site settings
title: Mon Ami Déco
email: contato@monamideco.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Color settings (hex-codes without the leading hash-tag)
color:
    primary: b03d11
    secondary: 335d69
    secondary-dark: 792a4a
    nav-background: rgba(237,237,237,0.8)

# Team names, titles and social links
people:
- name: Sabrina Guimarães
  pic: sabry.jpg
  position: Arquiteta & Coach Déco
  social:
    - title: facebook
      url: https://facebook.com/sabrina.guimaraes.94
    - title: linkedin
      url: https://br.linkedin.com/pub/sabrina-guimarães/14/448/a64

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/monamideco

# Postal address (add as many lines as necessary)
address:
  - line: Rio de Janeiro

# Build settings
markdown: kramdown
permalink: pretty
